PS_CLEAN_DATA = [
    {"cn": "秘境探險 4", "en": "Uncharted 4: A Thief's End"},
    {"cn": "秘境探險 失落遺產", "en": "Uncharted: The Lost Legacy"},
    {"cn": "秘境探險 1", "en": "Uncharted: Drake's Fortune"},
    {"cn": "秘境探險 2", "en": "Uncharted 2: Among Thieves"},
    {"cn": "秘境探險 3", "en": "Uncharted 3: Drake's Deception"},
    {"cn": "血源詛咒", "en": "Bloodborne"},
    {"cn": "最後生還者 重製版", "en": "The Last of Us Remastered"},
    {"cn": "最後生還者 第1部", "en": "The Last of Us Part I"},
    {"cn": "最後生還者 第2部", "en": "The Last of Us Part II"},
    {"cn": "對馬戰鬼", "en": "Ghost of Tsushima"},
    {"cn": "對馬戰鬼 導演剪輯版", "en": "Ghost of Tsushima Director's Cut"},
    {"cn": "漫威蜘蛛人", "en": "Marvel's Spider-Man"},
    {"cn": "蜘蛛人 邁爾斯", "en": "Marvel's Spider-Man: Miles Morales"},
    {"cn": "漫威蜘蛛人 2", "en": "Marvel's Spider-Man 2"},
    {"cn": "戰神", "en": "God of War"},
    {"cn": "戰神 諸神黃昏", "en": "God of War Ragnarök"},
    {"cn": "戰神 3 重製版", "en": "God of War III Remastered"},
    {"cn": "直到黎明", "en": "Until Dawn"},
    {"cn": "底特律 變人", "en": "Detroit: Become Human"},
    {"cn": "地平線 期待黎明", "en": "Horizon Zero Dawn"},
    {"cn": "地平線 西域禁地", "en": "Horizon Forbidden West"},
    {"cn": "拉捷特與克拉克", "en": "Ratchet & Clank"},
    {"cn": "拉捷特與克拉克 時空跳躍", "en": "Ratchet & Clank: Rift Apart"},
    {"cn": "往日不再", "en": "Days Gone"},
    {"cn": "惡名昭彰 第二之子", "en": "Infamous Second Son"},
    {"cn": "最後守護者", "en": "The Last Guardian"},
    {"cn": "汪達與巨像", "en": "Shadow of the Colossus"},
    {"cn": "跑車浪漫旅 7", "en": "Gran Turismo 7"},
    {"cn": "跑車浪漫旅 競速", "en": "Gran Turismo Sport"},
    {"cn": "死亡擱淺", "en": "Death Stranding"},
    {"cn": "死亡回歸", "en": "Returnal"},
    {"cn": "惡魔靈魂", "en": "Demon's Souls"},
    {"cn": "麻布仔大冒險", "en": "Sackboy: A Big Adventure"},
    {"cn": "FF7 重製版", "en": "Final Fantasy VII Remake"},
    {"cn": "FF7 重製版 尤菲", "en": "Final Fantasy VII Remake Intergrade"},
    {"cn": "FF7 重生", "en": "Final Fantasy VII Rebirth"},
    {"cn": "最終幻想 16", "en": "Final Fantasy XVI"},
    {"cn": "電馭叛客 2077", "en": "Cyberpunk 2077"},
    {"cn": "艾爾登法環", "en": "Elden Ring"},
    {"cn": "隻狼", "en": "Sekiro: Shadows Die Twice"},
    {"cn": "星際大戰 絕地倖存者", "en": "Star Wars Jedi: Survivor"},
    {"cn": "惡靈古堡 2 重製版", "en": "Resident Evil 2"},
    {"cn": "惡靈古堡 3 重製版", "en": "Resident Evil 3"},
    {"cn": "惡靈古堡 4 重製版", "en": "Resident Evil 4"},
    {"cn": "惡靈古堡 8", "en": "Resident Evil Village"},
    {"cn": "女神異聞錄 5 皇家版", "en": "Persona 5 Royal"},
    {"cn": "女神異聞錄 5", "en": "Persona 5"},
    {"cn": "P5S 女神異聞錄", "en": "Persona 5 Strikers"},
    {"cn": "P3R 女神異聞錄", "en": "Persona 3 Reload"},
    {"cn": "魔物獵人 世界", "en": "Monster Hunter: World"},
    {"cn": "魔物獵人 世界 冰原", "en": "Monster Hunter World: Iceborne"},
    {"cn": "仁王", "en": "Nioh"},
    {"cn": "仁王 2", "en": "Nioh 2"},
    {"cn": "鬼線東京", "en": "Ghostwire: Tokyo"},
    {"cn": "奇納 靈魂之橋", "en": "Kena: Bridge of Spirits"},
    {"cn": "Stray 浪貓", "en": "Stray"},
    {"cn": "人中之龍 0", "en": "Yakuza 0"},
    {"cn": "人中之龍 極", "en": "Yakuza Kiwami"},
    {"cn": "人中之龍 極 2", "en": "Yakuza Kiwami 2"},
    {"cn": "人中之龍 6", "en": "Yakuza 6: The Song of Life"},
    {"cn": "人中之龍 7", "en": "Yakuza: Like a Dragon"},
    {"cn": "人中之龍 7 外傳", "en": "Like a Dragon Gaiden: The Man Who Erased His Name"},
    {"cn": "人中之龍 8", "en": "Like a Dragon: Infinite Wealth"},
    {"cn": "審判之眼 死神的遺言", "en": "Judgment"},
    {"cn": "審判之逝 湮滅的記憶", "en": "Lost Judgment"},
    {"cn": "北斗如龍", "en": "Fist of the North Star: Lost Paradise"},
    {"cn": "控制", "en": "Control"},
    {"cn": "控制 終極版", "en": "Control Ultimate Edition"},
    {"cn": "刺客教條 幻象", "en": "Assassin's Creed Mirage"},
    {"cn": "刺客教條 維京紀元", "en": "Assassin's Creed Valhalla"},
    {"cn": "刺客教條 暗影者", "en": "Assassin's Creed Shadows"},
    {"cn": "碧血狂殺 2", "en": "Red Dead Redemption 2"},
    {"cn": "GTA 5", "en": "Grand Theft Auto V"},
    {"cn": "劍星", "en": "Stellar Blade"},
    {"cn": "奈克 2", "en": "Knack II"},
    {"cn": "骷髏戰士", "en": "MediEvil"},
    {"cn": "宇宙機器人", "en": "Astro Bot"},
    {"cn": "壁中精靈", "en": "Concrete Genie"},
    {"cn": "重力異想世界 2", "en": "Gravity Rush 2"},
    {"cn": "教團 1886", "en": "The Order: 1886"},
    {"cn": "駕駛俱樂部", "en": "Driveclub"},
    {"cn": "殺戮地帶 闇影墜落", "en": "Killzone Shadow Fall"},
    {"cn": "撕紙小郵差", "en": "Tearaway Unfolded"},
    {"cn": "異形 孤立", "en": "Alien: Isolation"},
    {"cn": "蝙蝠俠 阿卡漢騎士", "en": "Batman: Arkham Knight"},
    {"cn": "尼爾 自動人形", "en": "NieR: Automata"},
    {"cn": "死亡循環", "en": "Deathloop"},
    {"cn": "魔咒之地", "en": "Forspoken"},
    {"cn": "反重力賽車", "en": "WipEout Omega Collection"},
    {"cn": "全民高爾夫", "en": "Everybody's Golf"},
    {"cn": "勇者鬥惡龍 11", "en": "Dragon Quest XI: Echoes of an Elusive Age"},
    {"cn": "勇者鬥惡龍 怪物仙境 3", "en": "Dragon Quest Monsters: The Dark Prince"},
    {"cn": "毀滅全明星", "en": "Destruction AllStars"},
    {"cn": "風之旅人", "en": "Journey"},
    {"cn": "機器人機關", "en": "Crash Bandicoot N. Sane Trilogy"},
    {"cn": "復仇槍手", "en": "Hyrule Warriors: Definitive Edition"},
    {"cn": "雙人成行", "en": "It Takes Two"},
    {"cn": "喋血復仇", "en": "Back 4 Blood"},
    {"cn": "先遣者", "en": "Outriders"},
    {"cn": "眾神紀錄", "en": "Immortals Fenyx Rising"},
    {"cn": "遠方海岸", "en": "Far: Changing Tides"},
    {"cn": "太陽灰燼", "en": "Solar Ash"},
    {"cn": "無人深空", "en": "No Man's Sky"},
    {"cn": "全境封鎖 2", "en": "Tom Clancy's The Division 2"},
    {"cn": "極地戰嚎 6", "en": "Far Cry 6"},
    {"cn": "決勝時刻 現代戰爭 2", "en": "Call of Duty: Modern Warfare II"},
    {"cn": "小小夢魘 2", "en": "Little Nightmares II"},
    {"cn": "數碼寶貝 網路偵探", "en": "Digimon Story: Cyber Sleuth"},
    {"cn": "超級機器人大戰 T", "en": "Super Robot Wars T"},
    {"cn": "超級機器人大戰 30", "en": "Super Robot Wars 30"},
    {"cn": "鋼彈創壞者 4", "en": "Gundam Breaker 4"},
    {"cn": "機戰傭兵 6", "en": "Armored Core VI Fires of Rubicon"},
    {"cn": "浪人崛起", "en": "Rise of the Ronin"}
]