"""add intro column to eshop_mapping

Revision ID: 5f3471da3c56
Revises: cb847568461b
Create Date: 2026-03-23 02:26:53.599834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3471da3c56'
down_revision = 'cb847568461b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eshop_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eshop_mappings', schema=None) as batch_op:
        batch_op.drop_column('intro')

    # ### end Alembic commands ###
