"""allow nsuid and eshop_name to be nullable

Revision ID: 82e6d0d352bb
Revises: 
Create Date: 2026-03-17 18:09:50.751990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82e6d0d352bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eshop_mappings', schema=None) as batch_op:
        batch_op.alter_column('igdb_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('nsuid',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_eshop_mappings_game_name'))
        batch_op.drop_index(batch_op.f('ix_eshop_mappings_igdb_id'))
        batch_op.drop_index(batch_op.f('ix_eshop_mappings_nsuid'))
        batch_op.create_unique_constraint(None, ['igdb_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eshop_mappings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_eshop_mappings_nsuid'), ['nsuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_eshop_mappings_igdb_id'), ['igdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eshop_mappings_game_name'), ['game_name'], unique=False)
        batch_op.alter_column('nsuid',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('igdb_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
