"""empty message

Revision ID: cb847568461b
Revises: 82e6d0d352bb
Create Date: 2026-03-19 15:24:57.556662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb847568461b'
down_revision = '82e6d0d352bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eshop_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('english_name', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_eshop_mappings_title_id'), ['title_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eshop_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eshop_mappings_title_id'))
        batch_op.drop_column('english_name')
        batch_op.drop_column('title_id')

    # ### end Alembic commands ###
